### ISSUE TITLE
Unable to install lxml on M1 mac

### ISSUE THREAD

**Issue by transcendr** [Torantulino/Auto-GPT#16]
This install throws a couple different errors.

I tried another suggestion which gives the same result `arch -x86_64 pip3 install lxml`

python 3.8.9

any ideas?

```
Building wheel for lxml (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/z9/v8hgfs2527j8t9pv656k580w0000gn/T/pip-install-udz7nb_q/lxml/setup.py'"'"'; __file__='"'"'/private/var/folders/z9/v8hgfs2527j8t9pv656k580w0000gn/T/pip-install-udz7nb_q/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/z9/v8hgfs2527j8t9pv656k580w0000gn/T/pip-wheel-d6m9houy
       cwd: /private/var/folders/z9/v8hgfs2527j8t9pv656k580w0000gn/T/pip-install-udz7nb_q/lxml/
  Complete output (117 lines):
  Building lxml version 4.9.2.
  Building without Cython.
  Building against libxml2 2.9.4 and libxslt 1.1.29
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-arm64-3.8
  creating build/lib.macosx-10.14-arm64-3.8/lxml
```

**Comment by Torantulino** [comment]
> I don't personally know anything about Mac. Here's what the AI says:

The issue seems to be caused by the installation of the `lxml` package, not the code you have provided. The problem is related to building the package on your system, which might be caused by a missing or incompatible version of a required dependency.

Please try the following steps:

1. First, make sure you have installed the required dependencies: `libxml2` and `libxslt`:

   If you are using macOS, you can install these dependencies using Homebrew with the following commands:

   ```
   brew install libxml2
   brew install libxslt
   ```

   If you are using a Linux distribution, use the package manager for your distribution (e.g., `apt-get`, `yum`, `pacman`, etc.) to install `libxml2` and `libxslt`.

2. Make sure you have `lxml` version that match your python version

   You can try installing a different version of the package, based on your Python version. For example, if you are using Python 3.8, you can try:

   ```
   pip install lxml==4.9.2
   ```

**Comment by transcendr** [comment]
Hi, thanks for your quick response.  In the meantime I was doing some additional troubleshooting and eventually got it working.  Here's the steps I took:

1. upgraded from python 3.8.9 to 3.11 ( `brew update && brew install python@3.11` )
2. with that version of python I was able to install lxml without issue
3. However upon running -r req's again, I had errors from dependency conflicts.  I resolved those by using the suggested compatible versions, where final version of req's.txt looks like:

```
 1 ~ │ beautifulsoup4==4.9.3
   2   │ colorama==0.4.6
   3   │ googlesearch_python==1.1.0
   4   │ openai==0.27.0
   5   │ playsound==1.2.2
   6   │ readability_lxml==0.8.1
   7 ~ │ requests==2.25.1`
```

(excuse the formatting, I bat'd it)

An install from there worked and the system is so far running.  Will report back if anything comes up.  That said one thing I immediately noticed is that my AI had a step where an agent was to be created.  There are two options y (to proceed) and the other to exit.  Another option `e` to open the proposed agent creation command (or any command) and it edit in the default $EDITOR would be awesome.  It would be useful to tweak instructions to the agent that are slightly wrong.  Anyway, thanks again for your work on this. So far, it looks very interesting.

**Comment by Torantulino** [comment]
Glad you got it working, thanks for such a detailed response, that's really helpful.
Okay, looks like I need to update the requirements.txt

### Tasks from this issue:
- [ ] Update requirements.txt
- [ ] Suggest Python update?
- [ ] Add troubleshooting section?

As for your suggestion, I **love** it! Someone has recently suggested something similar, so I think I'll be able to kill two birds with one stone here. I'll get right onto implementing that after I push the big scary feature I'm currently working on...
**AI CODE EXECUTION**

**Comment by transcendr** [comment]
Wow dude you rock. You seem super motivated.  I'm really excited for where this could go.  Hopefully I'll have some time to contribute sooner than later.

 Cheers.

**Comment by Torantulino** [comment]
Thank you! If you get a chance, please share outputs of the program running in [discussions](https://github.com/Torantulino/Auto-GPT/discussions/14)!
It would be great to see people other than myself executing it.

Oh wow, a code contribution would be incredible. 🙏

Thanks for the kind words. 😊

**Comment by danielraffel** [comment]
on macOS - when I run `python main.py ` I get these errors

Traceback (most recent call last):
  File "/Users/username/Auto-GPT/scripts/main.py", line 3, in <module>
    import commands as cmd
  File "/Users/username/Auto-GPT/scripts/commands.py", line 1, in <module>
    import browse
  File "/Users/username/Auto-GPT/scripts/browse.py", line 1, in <module>
    from googlesearch import search
ModuleNotFoundError: No module named 'googlesearch

FWIW I do have Requirement already satisfied: googlesearch_python in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (1.1.0)

would love to try this again perhaps when these are updated
https://github.com/Torantulino/Auto-GPT/issues/16#issuecomment-1492947932

**Comment by microfx** [comment]
oh god... I'm again in python env version hell AAAAAAAAAAHHHHHHHHHHHH ... I have like 5 python versions installed – I will never understand how to manage this ... sad day for me.

**Comment by SurpriseMF3000** [comment]
> 1. upgraded from python 3.8.9 to 3.11 ( `brew update && brew install python@3.11` )

Worked for me;)

**Comment by basit26374** [comment]
I resolved the issue by upgrading my Python version from 3.8 to 3.11.
` brew update && brew install python@3.11 )`

Thanks @transcendr
